# Site
# repository: rollauda/cv
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rolland Auda
title: Professeur de philosophie 
subtitle: Écrivain jeunesse
# email: 
email: auda.rolland@condamine.edu.ec
email_title: Email
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://rollauda.github.io
website_title: Site des leçons

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  rollauda
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: rollauda.github.io
#  icon: fas fa-globe
#  url: https://rollauda.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Présentation
about_profile_image: images/photo.jpg
about_content: | # this will include new lines to allow paragraphs
  <br> Bonjour ! 
  
  Je suis professeur de philosophie au Lycée français La Condamine (Quito, Équateur). 

  Vous pouvez consulter mes cours de philosophie (Tronc commun et HLP), de cinéma (Spécialité CAV) et de droit (Option DGEMC) [sur cette autre page](https://rollauda.github.io){:target="_blank" }.

  Ci-dessous, vous trouverez [mon parcours](#parcours-professionnel), [mes actions pédagogiques](#actions-pédagogiques) et [mes diplômes](#diplômes).
  
  J'écris des [romans-jeunesse](#romans) publiés aux éditions Sarbacane, Casterman et Lunii.

content:
  - title: Parcours professionnel # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  
        title: Professeur de philosophie
        caption: 1997 → Aujourd'hui
        description: | # this will include new lines to allow paragraphs
          - **Équateur** (Quito) : professeur détaché
            - 2022 → Aujourd'hui 
          - **France** (Académies de Bordeaux et de Montpellier)
            - 2009 - 2018
          - **Algérie** (Alger)
            - 2007 - 2009
          - **Équateur** (Quito) : professeur résident
            - 2003-2006
          - **France** (Académies de Besançon et de Grenoble)
            - 1997 - 2002
      - layout: left
        border: weak
        title: Professeur d'H-G
        caption: 2018 - 2022
        description: | # this will include new lines to allow paragraphs
          - **Équateur** (Quito) : Professeur d'histoire-géographie en contrat local (niveaux 6°, 4°, 3°) 

      - layout: left
        title: Journaliste
        caption: 1995 - 1997
        description: | # this will include new lines to allow paragraphs
          - **Radio Marseillette** (Aude) : service civil : présentation du journal local et d'une émission littéraire
          - **Pigiste en presse écrite** (La Dépêche du Midi ; L’Audyssée des 7-13 ans) 

  - title: Actions pédagogiques # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Ateliers de philosophie 
        link: rollauda.github.io/pod
        link_text: Lien vers les ateliers
        # sub_title: 
        # caption: 2022 - 2024
        description: | # this will include new lines to allow paragraphs
            **Rencontres philosophiques entre élèves de Terminale et de CM2.**   
            Chaque année, mes élèves de Terminale se joignent à une classe de CM1-CM2 pour un atelier philosophie.  
            - 2024 : Qu'est-ce que la beauté ? (avec les classes d'Olivier Pie et Amandine Tarter)  
            - 2023 : Qu'est-ce qu'une grande personne ? (avec les classes d'Olivier Pie et Marion Huirois)
      - layout: left
        border: weak
        title: Podcasts d'élèves 
        link: rollauda.github.io/pod
        link_text: Lien vers les podcasts
        # caption: 2023 - 2024
        description: | # this will include new lines to allow paragraphs
           **Productions audio d'élèves dans le cadre des cours de philosophie (HLP)**  
            - Complément du cours de philosophie : "Doit-on avoir pitié ?"
            - Podcast commun HLP - SES : "Qui suis-je ?"

      - layout: left
        border: weak
        title: Reconstitutions de procès 
        link: rollauda.github.io/dgemc
        link_text: Site de l'option DGEMC
        # caption: 2022 - 2024
        description: | # this will include new lines to allow paragraphs
          **En Option DGEMC (Droit et Grands Enjeux du Monde Contemporain), j'organise chaque année avec les élèves la reconstitution d'un procès.**    
            - 2024 : Le procès de Jacqueline Sauvage
            - 2023 : L'Humanité contre la Nature

      - layout: left
        border: weak
        title: Organisation de conférences 
        link: rollauda.github.io/dgemc
        link_text: Site de l'option DGEMC
        # caption: 2022 - 2024
        description: | # this will include new lines to allow paragraphs
          **En Option DGEMC, j'organise chaque année avec les élèves une conférence afin d'interroger un thème contemporain sous l'angle du droit.**  
            - 2024 : Le dopage
            - 2023 : Le féminicide 

      - layout: left
        title: Ateliers d'écriture 
        # link: rollauda.github.io
        # link_text: rollauda.github.io
        # caption: 2015 - 2023
        description: | # this will include new lines to allow paragraphs
            - 2018 : Roman collectif de science fiction en 3° (Quito, Équateur)
            - 2015 : École primaire Calandreta de Nîmes (30)
            - 2010 - 2018 : Ateliers dans des salons du livre (Besançon, Troyes, Rennes)

  - title: Romans # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Sarbacane
        link: https://editions-sarbacane.com/auteurs/rolland-auda
        link_text: Ma page Sarbacane
        # caption: 2007 → Aujourd'hui
        description: | # this will include new lines to allow paragraphs
          - **Gringo Shaman** (2008)
          - **Le dévastateur** (2011)
          - **L'Équipée volage** (2013)
          - **Lola et la machine à laver le temps** (2016)
          - **Le Gouffre** (2018)
          - **Les Picapoches** (2021)

      - layout: left
        border: weak
        title: Casterman
        link: https://www.casterman.com/Jeunesse/Auteurs/auda-rolland
        link_text: Ma page Casterman
        # caption: 2021 → Aujourd'hui
        description: | # this will include new lines to allow paragraphs
          - **L'amie du sous-sol** (2020)
          - **La Vallée fantôme** (2022) 

      - layout: left
        title: Lunii
        link: https://lunii.com/fr-fr/luniistore-catalogue-flam/panique-robotique/
        link_text: Ma page Lunii
        # caption: 1995 - 1997
        description: | # this will include new lines to allow paragraphs
          - **Panique Robotique** (2023) : livre audio, à écouter sur l'appareil FLAM de l'éditeur Lunii
  
  - title: Diplômes
    layout: text
    #    link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
    #    link_text: Link Text
    #    additional_links:
    #      - title:  Github page for project (eg. sproogen/modern-resume-theme)
    #        icon: fab fa-github
    #        url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
    #      - title:  Github page for project (eg. sproogen/modern-resume-theme)
    #        icon: fab fa-github
    #        url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
    content: | # this will include new lines to allow paragraphs
      - Maîtrise de philosophie (1994)
      - CAPES de philosophie (1995)
      - Certification DNL espagnol / philosophie (2010)
      - Certification Cinéma-Audiovisuel (2019)

# Footer
footer_show_references: true
references_title: Réferences sur demande

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
