# Site
# repository: rollauda/cv
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rolland Auda
title: Professeur de philosophie et de cinéma
email: auda.rolland@condamine.edu.ec

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  rollauda
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: rollauda.github.io
#  icon: fas fa-globe
#  url: https://rollauda.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Présentation
about_profile_image: images/photo.jpg
about_content: | # this will include new lines to allow paragraphs
  <br> Bonjour. Je suis professeur de philosophie au Lycée français La Condamine (Quito, Équateur). 

  Vous pouvez découvrir mes cours de philosophie (Tronc commun et HLP), de cinéma (Spécialité CAV) et de droit (Option DGEMC) [sur cette autre page](https://rollauda.github.io){:target="_blank" }.

  Ci-dessous, vous trouverez [mon parcours](#parcours-professionnel), [mes actions pédagogiques](#actions-pédagogiques) et [mes diplômes](#diplômes).
  
  J'écris depuis 2007 des [romans-jeunesse](#romans) publiés aux éditions Sarbacane, Casterman et Lunii.

content:
  - title: Parcours professionnel # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Professeur de philosophie
        caption: 1997 → Aujourd'hui
        description: | # this will include new lines to allow paragraphs
          - **France** (Académies de Besançon et de Grenoble) :1997 - 2002
          - **Équateur** (Quito) : professeur résident, 2003-2006
          - **Algérie** (Alger) : 2007 - 2009
          - **France** (Académies de Bordeaux et de Montpellier) : 2009 - 2018
          - **Équateur** (Quito) : professeur détaché, 2022 → Aujourd'hui 

      - layout: left
        title: Professeur d'histoire-géographie
        caption: 2018 - 2022
        description: | # this will include new lines to allow paragraphs
          - **Équateur** (Quito) : Professeur en contrat local d'histoire-géographie (6°, 4°, 3°) 

      - layout: left
        title: Journaliste
        caption: 1995 - 1997
        description: | # this will include new lines to allow paragraphs
          - **Radio Marseillette** (Aude) : service civil : présentation du journal local et d'une émission littéraire
          - **Pigiste en presse écrite** (La Dépêche du Midi ; L’Audyssée des 7-13 ans) 

  - title: Actions pédagogiques # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ateliers philosophie 
        # link: rollauda.github.io
        # link_text: rollauda.github.io
        # sub_title: 
        caption: 2022 - 2024
        description: | # this will include new lines to allow paragraphs
            **Rencontres philosophiques entre élèves de Terminale et de CM2.**   
            Chaque année, mes élèves de Terminale se joigent à une classe de CM1-CM2 pour un atelier philosophie.  
            - 2023 : Qu'est-ce qu'une grande personne ? (avec les classes d'Olivier Pie et Marion Huirois)
            - 2024 : Qu'est-ce que la beauté ? (avec les classes d'Olivier Pie et Amandine Tarter)  
             
            Lien : [enregistrement 2023](https://drive.google.com/file/d/1W_BOIws6OlEpqjUhTjCl7a3OMDuoBlwr/view?usp=drive_link){:target="_blank" }

      - layout: left
        title: Podcasts d'élèves 
        link: rollauda.github.io
        # link_text: rollauda.github.io
        sub_title: Productions audio d'élèves dans le cadre des cours de philosophie (HLP)
        caption: 2023 - 2024
        description: | # this will include new lines to allow paragraphs
            Description

      - layout: left
        title: Reconstitutions de procès 
        link: rollauda.github.io
        # link_text: rollauda.github.io
        sub_title: EN Option DGEMC, nous avons reconstitué des procès.
        caption: 2022 - 2024
        description: | # this will include new lines to allow paragraphs
            - 2023 : L'Humanité contre la Nature
            - 2024 : Le procès de Jacqueline Sauvage

      - layout: left
        title: Organisation de conférences 
        link: rollauda.github.io
        # link_text: rollauda.github.io
        sub_title: EN Option DGEMC, nous avons organisé des conférences.
        caption: 2022 - 2024
        description: | # this will include new lines to allow paragraphs
            Description

  - title: Diplômes
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Maîtrise de philosophie (1994)
      - CAPES de philosophie (1995)
      - Certification DNL espagnol / philosophie (2010)
      - Certification Cinéma-Audiovisuel (2019)

# Footer
footer_show_references: true
references_title: Réferences sur demande

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
